environment: "local" #, prod
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
storage:
  user: postgres
  password: postgres
  host: postgres
  port: 5432
  db_name: subscriptions
  sslmode: disable
