environment: "local" #, prod
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
storage:
  user: postgres
  password: password
  host: localhost
  port: 5432
  db_name: subscriptions
  sslmode: "disable"
